version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   restart: always
  #   ports:
  #     - "1025:1025" #127.0.0.1:1025:1025
  #     - "8025:8025"
  # networks:
  #   - badgr

  minio:
    container_name: s3minio
    image: minio/minio:latest
    ports:
      - "${S3_PORT}:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --address ":9000" --console-address ":9001" /data
    # networks:
    #   - badgr

volumes:
  postgres_data:
  minio_storage:
